# Generated by Django 5.0.6 on 2024-06-05 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=20)),
                ('release_year', models.IntegerField()),
                ('body_style', models.CharField(max_length=15)),
                ('transmission', models.CharField(max_length=20)),
                ('mileage', models.IntegerField()),
                ('seating_capacity', models.IntegerField()),
                ('cargo_capacity', models.IntegerField()),
                ('car_dimension', models.CharField(max_length=30)),
                ('tyre_strength', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=35)),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
