# Generated by Django 5.0.6 on 2024-06-20 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0003_custform_profit_supplier_alter_car_model_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_id', models.IntegerField()),
                ('supplier_id', models.IntegerField()),
                ('cust_id', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        )
    #     migrations.CreateModel(
    #         name='Deal',
    #         fields=[
    #             ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
    #             ('model_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cargo.car')),
    #             ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cargo.supplier')),
    #         ],
    #     ),
     ]
