# Generated by Django 5.0.6 on 2024-06-20 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0004_sales_deal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='car_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cargo.car'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='cust_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cargo.custform'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='supplier_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cargo.supplier'),
        ),
    ]
