# Generated by Django 5.0.6 on 2024-06-20 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0005_alter_sales_car_id_alter_sales_cust_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='car_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sales',
            name='cust_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sales',
            name='supplier_id',
            field=models.IntegerField(),
        ),
    ]
