# # Generated by Django 5.0.6 on 2024-06-21 19:35

# from django.db import migrations, models


# class Migration(migrations.Migration):

#     dependencies = [
#         ('cargo', '0006_alter_sales_car_id_alter_sales_cust_id_and_more'),
#     ]

#     operations = [
#         migrations.RemoveField(
#             model_name='deal',
#             name='model_no',
#         ),
#         migrations.RemoveField(
#             model_name='deal',
#             name='supplier',
#         ),
#         migrations.AddField(
#             model_name='deal',
#             name='car_id',
#             field=models.IntegerField(blank=True, null=True),
#         ),
#         migrations.AddField(
#             model_name='deal',
#             name='supplier_id',
#             field=models.IntegerField(blank=True, null=True),
#         ),
#     ]
