# Generated by Django 5.0.6 on 2024-07-05 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0007_remove_deal_model_no_remove_deal_supplier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='model_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='custform',
            name='NIC',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='custform',
            name='address',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='custform',
            name='email',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='custform',
            name='f_name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='custform',
            name='l_name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='custform',
            name='phone_no',
            field=models.CharField(max_length=11),
        ),
        # migrations.AlterField(
        #     model_name='deal',
        #     name='car_id',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cargo.car'),
        # ),
        # migrations.AlterField(
        #     model_name='deal',
        #     name='supplier_id',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cargo.supplier'),
        # ),
        migrations.AlterField(
            model_name='profit',
            name='model_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='profit',
            name='profit',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='profit',
            name='year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sales',
            name='car_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cargo.car'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='cust_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cargo.custform'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='supplier_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cargo.supplier'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supp_address',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supp_email',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supp_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supp_phoneno',
            field=models.CharField(max_length=11),
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NIC', models.CharField(max_length=13)),
                ('f_name', models.CharField(max_length=10)),
                ('l_name', models.CharField(max_length=10)),
                ('NewCustomer_name', models.CharField(max_length=20)),
                ('NewCustomer_NIC', models.CharField(max_length=13)),
                ('model_name', models.CharField(max_length=10)),
                ('release_year', models.IntegerField()),
                ('cust_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cargo.custform')),
            ],
        ),
    ]
