# Generated by Django 5.0.6 on 2024-07-05 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0008_alter_car_model_name_alter_custform_nic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profit',
            name='profit',
            field=models.CharField(max_length=100),
        ),
    ]
