# # Generated by Django 5.0.6 on 2024-07-05 15:41

# from django.db import migrations, models


# class Migration(migrations.Migration):

#     dependencies = [
#         ('cargo', '0009_alter_profit_profit'),
#     ]

#     operations = [
#         migrations.AlterField(
#             model_name='deal',
#             name='car_id',
#             field=models.IntegerField(blank=True, null=True),
#         ),
#     ]
