# # Generated by Django 5.0.6 on 2024-07-05 15:46

# from django.db import migrations, models


# class Migration(migrations.Migration):

#     dependencies = [
#         ('cargo', '0010_alter_deal_car_id'),
#     ]

#     operations = [
#         migrations.AlterField(
#             model_name='deal',
#             name='car_id',
#             field=models.IntegerField(),
#         ),
#         migrations.AlterField(
#             model_name='deal',
#             name='supplier_id',
#             field=models.IntegerField(),
#         ),
#         migrations.AlterField(
#             model_name='sales',
#             name='car_id',
#             field=models.IntegerField(),
#         ),
#         migrations.AlterField(
#             model_name='sales',
#             name='cust_id',
#             field=models.IntegerField(),
#         ),
#         migrations.AlterField(
#             model_name='sales',
#             name='supplier_id',
#             field=models.IntegerField(),
#         ),
#     ]
