# # Generated by Django 5.0.6 on 2024-07-05 15:55

# from django.db import migrations, models


# class Migration(migrations.Migration):

#     dependencies = [
#         ('cargo', '0011_alter_deal_car_id_alter_deal_supplier_id_and_more'),
#     ]

#     operations = [
#         migrations.AlterField(
#             model_name='deal',
#             name='car_id',
#             field=models.IntegerField(blank=True, null=True),
#         ),
#         migrations.AlterField(
#             model_name='deal',
#             name='supplier_id',
#             field=models.IntegerField(blank=True, null=True),
#         ),
#     ]
