# Generated by Django 5.0.6 on 2024-07-05 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0013_alter_deal_car_id_alter_deal_supplier_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deal',
            old_name='car_id',
            new_name='car',
        ),
        migrations.RenameField(
            model_name='deal',
            old_name='supplier_id',
            new_name='supplier',
        ),
    ]
