# # Generated by Django 5.0.6 on 2024-07-05 16:30

# from django.db import migrations


# class Migration(migrations.Migration):

#     dependencies = [
#         ('cargo', '0016_alter_profit_profit'),
#     ]

#     operations = [
#         migrations.RenameField(
#             model_name='deal',
#             old_name='car_id',
#             new_name='car_id_id',
#         ),
#         migrations.RenameField(
#             model_name='deal',
#             old_name='supplier_id',
#             new_name='supplier_id_id',
#         ),
#     ]
