# # Generated by Django 5.0.6 on 2024-07-05 16:41

# from django.db import migrations, models


# class Migration(migrations.Migration):

#     dependencies = [
#         ('cargo', '0017_rename_car_id_deal_car_id_id_and_more'),
#     ]

#     operations = [
#         migrations.RemoveField(
#             model_name='deal',
#             name='car_id_id',
#         ),
#         migrations.RemoveField(
#             model_name='deal',
#             name='supplier_id_id',
#         ),
#         migrations.AddField(
#             model_name='deal',
#             name='car_id',
#             field=models.IntegerField(blank=True, null=True),
#         ),
#         migrations.AddField(
#             model_name='deal',
#             name='supplier_id',
#             field=models.IntegerField(blank=True, null=True),
#         ),
#         migrations.AlterField(
#             model_name='car',
#             name='model_name',
#             field=models.CharField(max_length=100),
#         ),
#         migrations.AlterField(
#             model_name='custform',
#             name='NIC',
#             field=models.IntegerField(),
#         ),
#         migrations.AlterField(
#             model_name='custform',
#             name='address',
#             field=models.CharField(max_length=100),
#         ),
#         migrations.AlterField(
#             model_name='custform',
#             name='email',
#             field=models.CharField(max_length=100),
#         ),
#         migrations.AlterField(
#             model_name='custform',
#             name='f_name',
#             field=models.CharField(max_length=100),
#         ),
#         migrations.AlterField(
#             model_name='custform',
#             name='l_name',
#             field=models.CharField(max_length=100),
#         ),
#         migrations.AlterField(
#             model_name='custform',
#             name='phone_no',
#             field=models.CharField(max_length=100),
#         ),
#         migrations.AlterField(
#             model_name='profit',
#             name='model_name',
#             field=models.CharField(max_length=100),
#         ),
#         migrations.AlterField(
#             model_name='profit',
#             name='profit',
#             field=models.CharField(max_length=100),
#         ),
#         migrations.AlterField(
#             model_name='profit',
#             name='year',
#             field=models.CharField(max_length=100),
#         ),
#         migrations.AlterField(
#             model_name='sales',
#             name='car_id',
#             field=models.IntegerField(),
#         ),
#         migrations.AlterField(
#             model_name='sales',
#             name='cust_id',
#             field=models.IntegerField(),
#         ),
#         migrations.AlterField(
#             model_name='sales',
#             name='supplier_id',
#             field=models.IntegerField(),
#         ),
#         migrations.AlterField(
#             model_name='supplier',
#             name='supp_address',
#             field=models.CharField(max_length=100),
#         ),
#         migrations.AlterField(
#             model_name='supplier',
#             name='supp_email',
#             field=models.CharField(max_length=100),
#         ),
#         migrations.AlterField(
#             model_name='supplier',
#             name='supp_name',
#             field=models.CharField(max_length=100),
#         ),
#         migrations.AlterField(
#             model_name='supplier',
#             name='supp_phoneno',
#             field=models.CharField(max_length=100),
#         ),
#     ]
